<?php

namespace Plugin\SendGridLight\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SendGridLightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SendGridLightRepository extends EntityRepository
{
}
